name: Deploy Hauierz Frontend

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy_Frontend
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Setup Surge
        run:  npm install --global surge
      - name: Execute Deployment with Surge
        run:  surge ./ codics-test-git.surge.sh --token ${{ secrets.SURGE_DEPLOYMENT_SECRET }} 
